---
lnk-ceri-conseil: "https://e-doc.univ-avignon.fr/ceri/elections-des-representants-des-personnels-et-des-usagers-au-conseil-de-composante-centre-denseignement-et-de-recherche-en-informatique-scrutin-du-mardi-12-mars-2024-8h00-au-mercredi-13-mars-2024-17/"
lnk-ceri-cmi: "https://ceri.univ-avignon.fr/formations/cursus-master-ingenierie-en-informatique/"
bde-gh: "https://github.com/bde-ceri"
